# Generated by Django 4.2 on 2023-04-29 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_alter_project_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(
                verbose_name=datetime.datetime(
                    2023, 4, 29, 21, 26, 18, 893956, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("High", "H"), ("Medium", "M"), ("Low", "L")],
                default="M",
                max_length=10,
            ),
        ),
    ]
