# Generated by Django 4.2 on 2023-04-30 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_alter_project_deadline_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 30, 10, 13, 35, 90709, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(
                verbose_name=datetime.datetime(
                    2023, 4, 30, 10, 13, 35, 87925, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
