# Generated by Django 4.2 on 2023-04-30 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0014_progress_estimated_alter_progress_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 30, 10, 23, 42, 610225, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(
                verbose_name=datetime.datetime(
                    2023, 4, 30, 10, 23, 42, 607456, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
