# Generated by Django 4.2 on 2023-04-30 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_alter_progress_date_alter_project_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="progress",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 4, 30, 10, 31, 7, 913414, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(
                verbose_name=datetime.datetime(
                    2023, 4, 30, 10, 31, 7, 910597, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
