# Generated by Django 4.2 on 2023-05-01 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0019_alter_project_deadline_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="deadline",
            field=models.DateField(
                verbose_name=datetime.datetime(
                    2023, 5, 1, 15, 32, 43, 770587, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
